Creating test
fprime-community/fpp pull request #253
Opened 2023-05-14 10:16 UTC by SMorettini

### Problem

The generation of the equal operator of `.cpp` for the following fpp
```
struct Modules4 {
  arr1: [3] M.Modules2
  arr2: [6] M.Modules2
}
```
is 
```
bool Modules4 ::
  operator==(const Modules4& obj) const
{
  // Compare non-array members
  if (!(

  )) {
    return false;
  }

  // Compare array members
...
```

The first if is empty and doesn't compile.

# Solution

I change the fpp-to-cpp to generate correct code also if there are no non-array members. 

# Note: it's my first time working with Scala, let me know if I should make the change using a different approach

2023-05-15 15:52 UTC, bocchino requested changes
Good catch! Looks good. Just a couple of formatting issues.

2023-05-15 15:52 UTC, bocchino commented on compiler/lib/src/main/scala/codegen/CppWriter/StructCppWriter.scala
> +        if nonArrayMemberNames.length >0 then List(
Please add a space between > and 0.

2023-05-17 06:52 UTC, SMorettini commented
I apply the formatting changes suggested

2023-05-17 16:21 UTC, bocchino approved these changes
Looks good!

2023-05-17 16:40 UTC, merged